
services:

  db:
    image: mariadb:latest
    container_name: mariadb-annonces
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql/data:rw
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: 'annonces-db'
    networks:
      - annonces-dev

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-annonces
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - annonces-dev

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq-annonces
    ports: [ 5672, 15672 ]
    restart: always
    networks:
      - annonces-dev

  mailer:
    image: axllent/mailpit
    container_name: mailpit-annonces
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - annonces-dev

  redis:
    image: redis:5-alpine
    container_name: redis-annonces
    ports: [ "6379" ]
    networks:
      - annonces-dev


volumes:
  db-data:
networks:
  annonces-dev:

